// Slide deck content for /present.
// Each slide is a typed variant. Order in this array IS the deck order.

export type Slide =
  | { kind: "title"; eyebrow: string; title: string; subtitle: string; date: string; author: string }
  | { kind: "section"; index: string; title: string; subtitle: string }
  | { kind: "agent"; slug: string; name: string; vendor: string; tier: string; surface: string; lifecycle: string; approvals: string; artifacts: string; tldr: string }
  | { kind: "dimension"; index: string; title: string; subtitle: string; patterns: { name: string; agents: string; tradeoff: string }[] }
  | { kind: "recap"; title: string; subtitle: string; items: { label: string; body: string }[] }
  | { kind: "outro"; title: string; body: string; cta: string };

// ---------- Audience tier classification (mirrors main page) ----------
const TIER: Record<string, string> = {
  cursor: "Developer · Prosumer",
  "chatgpt-agent": "Consumer · Prosumer",
  "claude-code": "Developer",
  devin: "Enterprise · Developer",
  "ms-scout": "Consumer · Enterprise",
  "perplexity-computer": "Consumer · Prosumer",
  manus: "Prosumer · Consumer",
  "replit-agent": "Prosumer · Consumer",
  v0: "Prosumer · Developer",
  genspark: "Consumer · Prosumer",
  aider: "Developer",
  jules: "Developer",
  lovable: "Prosumer · Consumer",
  bolt: "Prosumer · Developer",
  cline: "Developer",
  "amazon-q": "Enterprise · Developer",
  "langgraph-studio": "Developer · Enterprise",
  openhands: "Developer · Enterprise",
  continue: "Developer",
  crewai: "Enterprise · Developer",
  autogen: "Developer",
  "swe-agent": "Developer (Research)",
  autogpt: "Prosumer · Developer",
  goose: "Developer · Prosumer",
};

// ---------- 24 agent walkthrough slides ----------
const AGENTS: { slug: string; name: string; vendor: string; surface: string; lifecycle: string; approvals: string; artifacts: string; tldr: string }[] = [
  {
    slug: "cursor",
    name: "Cursor",
    vendor: "Anysphere",
    surface: "IDE (VS Code fork) + web Mission Control",
    lifecycle: "Live output stream + snapshot timeline you can scrub back",
    approvals: "Per-checkpoint diff Accept/Reject; background runs pause only on blockers",
    artifacts: "Inline diff gallery in the editor — every change is reviewable",
    tldr: "Two modes — synchronous co-pilot and async background agent — fused through one Mission Control dashboard. The state-machine timeline is the standout idea.",
  },
  {
    slug: "chatgpt-agent",
    name: "ChatGPT Agent",
    vendor: "OpenAI",
    surface: "Conversational web/desktop chat with embedded browser",
    lifecycle: "Inline status pills ('thinking', 'browsing'), with collapsible action log",
    approvals: "Risk-tiered — irreversible actions (payments, sends) bubble a confirmation modal",
    artifacts: "Deliverable cards inline in chat; downloadable files and saved tasks",
    tldr: "Consumer-grade approval UX done well: low-risk actions stream silently, high-risk ones interrupt with a clean modal showing exactly what's about to happen.",
  },
  {
    slug: "claude-code",
    name: "Claude Code",
    vendor: "Anthropic",
    surface: "Terminal, IDE, web, Slack — same agent across surfaces",
    lifecycle: "Plan → execute → review flow with explicit checkpoints",
    approvals: "Plan-then-execute; per-action confirmations on file writes by default",
    artifacts: "Auto-PRs on GitHub; inline diffs in terminal/IDE; conversation summaries",
    tldr: "Surface-agnostic. The same agent state syncs between terminal, IDE, and Slack — a strong bet that 'where' you manage agents is fluid, not fixed.",
  },
  {
    slug: "devin",
    name: "Devin",
    vendor: "Cognition Labs",
    surface: "Web dashboard + native desktop ('Devin Desktop' / Windsurf)",
    lifecycle: "Three-pane workspace: sessions list, agent narration, live workspace view",
    approvals: "Mostly autonomous; pauses with a 'needs input' state and Slack ping",
    artifacts: "GitHub PRs, test reports, screenshots — surfaced as Devin-authored summaries",
    tldr: "Treats the agent as an engineer — Sessions, Wiki, Review. The visual metaphor is 'watch a coworker work,' not 'drive a tool.'",
  },
  {
    slug: "ms-scout",
    name: "Microsoft Scout",
    vendor: "Microsoft Copilot",
    surface: "Always-on desktop agent (Windows 11)",
    lifecycle: "Activity feed in a dedicated panel; 'co-create' canvas for shared edits",
    approvals: "Risk-tiered with OS-level prompts; agent actions logged centrally",
    artifacts: "Documents, automations, M365 changes — all link back to source files",
    tldr: "Bets that the agent layer belongs in the OS, not the browser. Scout is what Windows looks like when an agent is a first-class peer to apps.",
  },
  {
    slug: "perplexity-computer",
    name: "Perplexity Computer",
    vendor: "Perplexity",
    surface: "Web app with task-centric sidebar + browser canvas",
    lifecycle: "Stepped task plan with sub-steps; live cursor on a virtual browser",
    approvals: "Plan-then-execute; confirmations for purchases/sends",
    artifacts: "Inline deliverables in the conversation (files, charts, websites)",
    tldr: "Tasks are the unit of work, not chats. The sidebar is a queue of named tasks you can pause, resume, schedule, or share.",
  },
  {
    slug: "manus",
    name: "Manus",
    vendor: "Manus (acquired by Meta)",
    surface: "Web app with prompt bar + 'session' workspace",
    lifecycle: "Step-by-step plan, then live execution log inside the session",
    approvals: "Mostly autonomous; per-tool approvals available in agent settings",
    artifacts: "Slides, websites, desktop apps, designs — each rendered in a viewer pane",
    tldr: "Prosumer-first general agent. The home screen is one prompt + quick-start verbs ('Create slides', 'Build website') — task type, not chat history.",
  },
  {
    slug: "replit-agent",
    name: "Replit Agent",
    vendor: "Replit",
    surface: "Web IDE / browser",
    lifecycle: "Kanban-ish board of build steps + live preview pane",
    approvals: "Checkpoint approvals before deploys / database writes",
    artifacts: "Running app preview, package changes, deployment artifacts",
    tldr: "The agent IS the IDE for non-developers. Building, previewing, and shipping are one flow — and the agent narrates the entire build.",
  },
  {
    slug: "v0",
    name: "v0",
    vendor: "Vercel",
    surface: "Web app with chat + live preview",
    lifecycle: "Conversation-driven; each turn replaces the preview with new output",
    approvals: "Full autonomy on UI generation; commits go through Vercel/Git flow",
    artifacts: "Live React preview + code panel; deploy with one click",
    tldr: "Two-pane is the whole story: type on the left, see it on the right. Iteration speed > approval density.",
  },
  {
    slug: "genspark",
    name: "Genspark Super Agent",
    vendor: "Genspark",
    surface: "Web 'Workspace 4.0' — sidebar of Skills, Workflows, Drive",
    lifecycle: "Workflow graphs + sub-agent traces; each step is inspectable",
    approvals: "Configurable per skill; defaults to autonomous",
    artifacts: "Slides, reports, audio, video — bundled as 'workflow output'",
    tldr: "Multi-modal output is the differentiator. You can ask for a deck, a podcast, and a research brief in one turn — and watch each branch run.",
  },
  {
    slug: "aider",
    name: "Aider",
    vendor: "Open source (Paul Gauthier)",
    surface: "Terminal — pure REPL",
    lifecycle: "Conversational with explicit /commands and ephemeral edits",
    approvals: "Confirm-before-commit by default; diffs shown inline in the terminal",
    artifacts: "Git commits with structured messages; repo-map context",
    tldr: "Proof that terminal-native UX still wins for the 'edit-my-repo' use case. No GUI, but enormous trust signals via diffs and commits.",
  },
  {
    slug: "jules",
    name: "Google Jules",
    vendor: "Google",
    surface: "Web app + CLI",
    lifecycle: "Plan-then-execute with explicit task tags ('Bug Fixing', 'Version Bump')",
    approvals: "Plan approval up front, then asynchronous execution",
    artifacts: "GitHub PRs, code reviews, scheduled task runs",
    tldr: "Async-first. The plan slide IS the spec — you approve a task, walk away, and get a PR. Closest to 'email an engineer' as a UX metaphor.",
  },
  {
    slug: "lovable",
    name: "Lovable",
    vendor: "Lovable",
    surface: "Web app with chat + canvas preview",
    lifecycle: "Plan Mode (review before run) + Agent Mode (autonomous) + Subagents",
    approvals: "User picks mode per project; Plan Mode is the default for big changes",
    artifacts: "Live web app preview; database, auth, deploys handled inline",
    tldr: "Explicit mode picker — same UI, different autonomy levels. A clean answer to 'how do I trust this?': you choose how much.",
  },
  {
    slug: "bolt",
    name: "Bolt.new",
    vendor: "StackBlitz",
    surface: "Web IDE with chat + WebContainer runtime",
    lifecycle: "Streamed file writes + terminal output side-by-side",
    approvals: "Mostly autonomous; ImportFigma/GitHub modals for source intake",
    artifacts: "Live preview, downloadable project zip, deploy-to-Netlify",
    tldr: "Speed-first. The agent skips ceremony — the UI is mostly the running app. Approval surface is minimal by design.",
  },
  {
    slug: "cline",
    name: "Cline",
    vendor: "Cline (open source)",
    surface: "VS Code extension + CLI + SDK",
    lifecycle: "Live action stream with thinking/tool calls inline",
    approvals: "Per-action confirmation by default; configurable auto-approve lists",
    artifacts: "File diffs in the editor; terminal output; MCP-style tool I/O",
    tldr: "Most transparent UX in the set. Every model thought and every tool call is visible — and every step is gated unless you opt out.",
  },
  {
    slug: "amazon-q",
    name: "Amazon Q Developer",
    vendor: "AWS",
    surface: "IDE plugin (JetBrains, VS Code) + AWS console",
    lifecycle: "Step plan with checkpoint cards; activity feed in the console",
    approvals: "Risk-tiered with IAM-aware gates for cloud actions",
    artifacts: "Code suggestions, PRs, AWS resource changes — with cost previews",
    tldr: "Enterprise approval UX done seriously. Every cloud action shows the IAM impact, cost delta, and rollback option before execution.",
  },
  {
    slug: "langgraph-studio",
    name: "LangGraph Studio",
    vendor: "LangChain",
    surface: "Standalone web IDE for graph-based agents",
    lifecycle: "DAG view of the agent — each node is a step, each edge is a transition",
    approvals: "Interrupt + resume from any node; human-in-the-loop is a graph primitive",
    artifacts: "Traces, runs, threads, assistants — all queryable",
    tldr: "Builds the visual language for agents-as-state-machines. If you've ever debugged a stuck agent, this is what you wished you had.",
  },
  {
    slug: "openhands",
    name: "OpenHands",
    vendor: "All Hands AI (open source)",
    surface: "Agent Canvas — web app with multi-agent boards",
    lifecycle: "Conversation list + canvas of agent runs; each run has its own thread",
    approvals: "Critic agent supervises; user reviews flagged steps",
    artifacts: "Code, files, terminal output — all attached to runs",
    tldr: "Multi-agent done coherently. The Canvas is a shared board where Claude Code, Codex, Gemini CLI, and OpenHands all coexist as peer agents.",
  },
  {
    slug: "continue",
    name: "Continue.dev",
    vendor: "Continue (acquired by Cursor)",
    surface: "VS Code / JetBrains extension + 'Mission Control' web dashboard",
    lifecycle: "Per-agent runs grouped by repo and trigger",
    approvals: "Per-action by default in IDE; auto-approve rules in Mission Control",
    artifacts: "PRs, suggestions, scheduled background runs",
    tldr: "First serious 'agents at team scale' UI — Mission Control is what an engineering org needs when 12 agents are running across 40 repos.",
  },
  {
    slug: "crewai",
    name: "CrewAI Studio",
    vendor: "CrewAI",
    surface: "Web Studio (No Code + CLI)",
    lifecycle: "Crew of agents with role/task graphs and traces",
    approvals: "Human-in-the-loop nodes inserted into crew flows",
    artifacts: "Traces, outputs, monitoring dashboards in the control plane",
    tldr: "Enterprise multi-agent: you don't talk to an agent, you compose a team. Hand-offs and traces are first-class — the UI looks like a workflow tool, not a chat.",
  },
  {
    slug: "autogen",
    name: "AutoGen Studio",
    vendor: "Microsoft Research",
    surface: "Local web app (Team Builder + Playground)",
    lifecycle: "Drag-and-drop team graph; interactive playground for runs",
    approvals: "Human-in-the-loop via AG-UI; configurable per agent",
    artifacts: "Saved team configs, traces, runs — exportable as JSON",
    tldr: "Research-grade composer. The Team Builder turned multi-agent assembly into a visual primitive — much like Node-RED did for IoT flows.",
  },
  {
    slug: "swe-agent",
    name: "SWE-agent",
    vendor: "Princeton NLP",
    surface: "CLI (primary) + experimental Web UI",
    lifecycle: "Step-by-step trajectory log; each tool call is an annotated event",
    approvals: "Fully autonomous; designed for benchmarks, not interactive use",
    artifacts: "Trajectories, patches, evaluation logs — for reproducibility",
    tldr: "Research artifact, not consumer product. Worth studying as the source of many trajectory-log patterns that surface in commercial UIs.",
  },
  {
    slug: "autogpt",
    name: "AutoGPT Platform",
    vendor: "Significant Gravitas",
    surface: "Web platform — blocks, workflows, library",
    lifecycle: "Block-based workflow runs with status and output per block",
    approvals: "Per-block configurable; some blocks need credentials",
    artifacts: "Output files, briefings, automations triggered on schedules",
    tldr: "Closest to a consumer agent app store. The home is 'pick a quick action' (Brief me, Watch competitors) — agents as appliances, not chats.",
  },
  {
    slug: "goose",
    name: "Goose",
    vendor: "Block / AAIF",
    surface: "Native desktop app + CLI + API",
    lifecycle: "Conversation with tool-use cards; sessions persist across restarts",
    approvals: "Per-tool by default; auto-approve for trusted MCP extensions",
    artifacts: "Local files, code, command output — runs on user's machine",
    tldr: "Local-first agent. Open source, MCP-native, and lives in the OS — the antithesis of cloud-tethered consumer agents.",
  },
];

// ---------- Dimension recap slides ----------
const DIMENSIONS = [
  {
    index: "D1",
    title: "Task Lifecycle",
    subtitle: "How agents communicate 'what they're doing right now'",
    patterns: [
      { name: "Live Activity Stream", agents: "Cursor · Cline · Aider · SWE-agent", tradeoff: "Max transparency, but pure noise to non-developers." },
      { name: "Plan-Then-Execute Card", agents: "Jules · Lovable · Claude Code · Perplexity Computer", tradeoff: "Trust-building, but users rubber-stamp plans." },
      { name: "Timeline Scrubber", agents: "Cursor · Devin · Manus · LangGraph", tradeoff: "Transformative for power users; baffling for consumers." },
      { name: "Three-Pane Workspace", agents: "Devin · Claude Code · v0 · Perplexity Computer", tradeoff: "Right for sustained artifacts. Wrong without one." },
      { name: "Kanban / Task Board", agents: "Replit · ChatGPT Agent · CrewAI", tradeoff: "Great for parallelism. Loses granularity." },
    ],
  },
  {
    index: "D2",
    title: "Approval Models",
    subtitle: "When the agent stops and asks",
    patterns: [
      { name: "Per-Action Confirmation", agents: "Cline · Claude Code · Continue", tradeoff: "Safe, but kills momentum after the 20th click." },
      { name: "Checkpoint Approval", agents: "Cursor · Replit · Lovable", tradeoff: "Right rhythm. Hard to define a good checkpoint." },
      { name: "Risk-Tiered Prompts", agents: "ChatGPT Agent · Amazon Q · MS Scout", tradeoff: "Best UX when the risk model is well-calibrated." },
      { name: "Full Autonomy + Interrupt", agents: "Devin · Manus · Bolt · v0", tradeoff: "Fastest. Catastrophic when wrong." },
      { name: "Async / Email-First", agents: "Jules · Devin · AutoGPT", tradeoff: "Best for big tasks. Wrong UX for quick edits." },
    ],
  },
  {
    index: "D3",
    title: "Artifact Surfacing",
    subtitle: "How the work product becomes inspectable",
    patterns: [
      { name: "Inline Diff Gallery", agents: "Cursor · Aider · Cline · Claude Code", tradeoff: "Truth at the line level. Useless if you can't read code." },
      { name: "Live Preview + Code Panel", agents: "v0 · Bolt · Lovable · Replit", tradeoff: "Outcome-first. Hard to debug when the preview lies." },
      { name: "Deliverable Card", agents: "ChatGPT Agent · Manus · Genspark · Perplexity", tradeoff: "Consumer-friendly. Hides the work." },
      { name: "Auto-PR / Auto-Commit", agents: "Devin · Jules · Continue · Cursor BG", tradeoff: "Best when the PR is the deliverable." },
      { name: "Specialized Canvas", agents: "OpenHands · Genspark · Manus", tradeoff: "Multi-modal output needs multi-modal viewers." },
    ],
  },
  {
    index: "D4",
    title: "Many Agents",
    subtitle: "How you manage parallelism",
    patterns: [
      { name: "Agent Inbox / List", agents: "Continue Mission Control · Devin Sessions · LangGraph", tradeoff: "Familiar. Becomes a graveyard at scale." },
      { name: "Sidebar Rail", agents: "Perplexity Computer · Manus · Cursor", tradeoff: "Always visible. Eats screen real estate." },
      { name: "Monitoring Dashboard", agents: "CrewAI · LangSmith · Amazon Q", tradeoff: "Enterprise truth. Wrong for one user, one task." },
      { name: "Graph / DAG View", agents: "LangGraph · AutoGen · CrewAI", tradeoff: "Honest about complexity. Requires literacy." },
      { name: "Schedules Page", agents: "Perplexity Computer · Continue · AutoGPT", tradeoff: "The future of consumer agents. Today, mostly hidden." },
    ],
  },
  {
    index: "D5",
    title: "Bubble Up",
    subtitle: "How agents reach you when you're elsewhere",
    patterns: [
      { name: "OS-Native Notifications", agents: "ChatGPT Agent · Goose · Scout", tradeoff: "Right for one user. Doesn't scale to teams." },
      { name: "Slack / Email Handoff", agents: "Devin · Claude Code · Jules", tradeoff: "Meets users where they are. Adds a delivery lag." },
      { name: "Status Dots / Badges", agents: "Cursor · Cline · Continue", tradeoff: "Subtle. Easy to miss the urgent ones." },
      { name: "Async Digest", agents: "Continue · AutoGPT · Perplexity scheduled tasks", tradeoff: "Reduces interruption. Decisions arrive cold." },
      { name: "Decision-Time Nudges", agents: "Amazon Q · Lovable · MS Scout", tradeoff: "Best when the agent knows what a 'decision' looks like." },
    ],
  },
];

export const slides: Slide[] = [
  {
    kind: "title",
    eyebrow: "Field Report",
    title: "How Agent Management Looks Today",
    subtitle: "24 products. 5 dimensions. One question — what should this look like inside Chrome.",
    date: "June 2026",
    author: "Magnus Borg · AI Product Strategy",
  },
  {
    kind: "section",
    index: "Part 1",
    title: "The Walkthrough",
    subtitle: "Twenty-four agent products, one screen each. What they look like, what they bet on, and where they diverge.",
  },
  ...AGENTS.map<Slide>((a) => ({
    kind: "agent",
    slug: a.slug,
    name: a.name,
    vendor: a.vendor,
    tier: TIER[a.slug] ?? "Mixed",
    surface: a.surface,
    lifecycle: a.lifecycle,
    approvals: a.approvals,
    artifacts: a.artifacts,
    tldr: a.tldr,
  })),
  {
    kind: "section",
    index: "Part 2",
    title: "The Patterns",
    subtitle: "Five dimensions, twenty-five recurring patterns. Where the industry agrees, where it splits, and what the tradeoffs are.",
  },
  ...DIMENSIONS.map<Slide>((d) => ({
    kind: "dimension",
    index: d.index,
    title: d.title,
    subtitle: d.subtitle,
    patterns: d.patterns,
  })),
  {
    kind: "recap",
    title: "Six things to take to Chrome",
    subtitle: "Distilled from the 24 products — what the consumer browser-native agent should adopt.",
    items: [
      { label: "01", body: "Task as the unit of work — not chat. Each task has a name, an owner, a status, and a place." },
      { label: "02", body: "One sidebar rail. The agent layer lives at the OS-level, not buried in a tab." },
      { label: "03", body: "Risk-tiered approvals. Reversible: silent. Costs money or sends: confirm. Touches identity: full review." },
      { label: "04", body: "Deliverable cards, not transcripts. Consumers want the result, with the work inspectable on demand." },
      { label: "05", body: "Decision-time nudges only. No badges, no buzz unless the agent is genuinely waiting on you." },
      { label: "06", body: "Schedules and reruns visible. The agent's calendar is as important as the user's." },
    ],
  },
  {
    kind: "outro",
    title: "Thanks.",
    body: "Full taxonomy, agent grid, and the Chrome proposal are at the link below. The deck is a tour. The site is the reference.",
    cta: "agent-ux-field-report.vercel.app",
  },
];
